### PR TITLE
Update minimum Python version to 3.9 in the configuration

### LINKED ISSUE #136: [TODO] Complete dropping support for Python 3.8
https://github.com/python/cherry-picker/pull/133 did this for CI already, but there are two pieces of the metadata that still advertise 3.8: `Require-Python` and Trove classifiers.

* https://github.com/python/cherry-picker/blob/e2540af/pyproject.toml#L13
* https://github.com/python/cherry-picker/blob/e2540af/pyproject.toml#L18

### PR DESCRIPTION
**Pull request by OlenaYefymenko**
🍒Update minimum Python version to 3.9 in the configuration

Resolves #136

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for the PR!

There's some linting to fix.

Please could you run:


```sh
python -m pip install pre-commit
pre-commit run --all-files
```

Or if you use uv, something like this:

```sh
uvx pre-commit run --all-files
```

And commit the changed file?

**Comment by OlenaYefymenko** [comment]
> Thanks for the PR!
> 
> There's some linting to fix.
> 
> Please could you run:
> 
> ```shell
> python -m pip install pre-commit
> pre-commit run --all-files
> ```
> 
> Or if you use uv, something like this:
> 
> ```shell
> uvx pre-commit run --all-files
> ```
> 
> And commit the changed file?

Thank you for the feedback!
Yes, I can run `pre-commit tool`
Please advise, should I make changes for `test_cherry_picker.py` within this PR, or is it better to open a new PR?
I worry about atomic, this is formatted changes and not connected with the Python version.

**Comment by zware** [comment]
IIUC the formatting changes are a direct result of no longer supporting 3.8, so I think it's fine to include them here.

Separately, it looks like the pre-commit configuration could stand an update (which should be a separate PR :))

**Comment by OlenaYefymenko** [comment]
> IIUC the formatting changes are a direct result of no longer supporting 3.8, so I think it's fine to include them here.
> 
> Separately, it looks like the pre-commit configuration could stand an update (which should be a separate PR :))

Thank you for pointing, I added this change.

**Review by zware — APPROVED** [review]

**Review by hugovk — APPROVED** [review]
Thank you for your contribution! 🎃🍒

**Comment by webknjaz** [comment]
@hugovk perhaps, somebody has to enable the pre-commit.ci app for this repo, eh?

**Comment by hugovk** [comment]
Good idea, I sent a request via https://pre-commit.ci/ to enable this repo. @JacobCoffee, please can you accept it?

**Comment by JacobCoffee** [comment]
@hugovk done

**Comment by hugovk** [comment]
Thanks!

**Pull request merged**
