### PR TITLE
Use ``tomli`` and ``tomllib`` instead of ``toml``

### LINKED ISSUE #59: Consider switching from `toml` to `tomli`
`toml` was last released on 02.11.2020: https://pypi.org/project/toml/#history
There are multiple known bugs: https://github.com/uiri/toml/issues

Maintainer is not supporting their project: https://github.com/uiri/toml/issues/361

Multiple big projects like [`mypy`](https://github.com/python/mypy/blob/1ccefbdff922b502637009a77632a2be10256297/setup.py#L201), [`black`](https://github.com/psf/black/blob/31fe97e7ce1055debaa54bed9c63e252508a9a75/setup.py#L102), [`typeshed`](https://github.com/python/typeshed/blob/494481a0aed2ef0e00bbe190476ace0b8261bce6/requirements-tests.txt#L10) have already switched. 

The transition seems to be rather simple: basically swap `import toml` with `import tomli` and use a proper `encoding` when calling `loads`.

Related: https://www.python.org/dev/peps/pep-0680/

If this is something you think should be done, I can send a PR.

### PR DESCRIPTION
**Pull request by DanielNoord**
Closes #59.

Did this in a similar way as many other packages or doing this. If the `sys` guard is not desired I'll obviously remove it.

### CODE REVIEW

**Comment by hugovk** [comment]
The `sys` guard is good, it'll be easy to find and remove when dropping support for 3.10 and older.

Please could you add `3.11-dev` to `.github/workflows/main.yml` so we test on the 3.11 pre-release as well?

**Comment by DanielNoord** [comment]
> The `sys` guard is good, it'll be easy to find and remove when dropping support for 3.10 and older.
> 
> Please could you add `3.11-dev` to `.github/workflows/main.yml` so we test on the 3.11 pre-release as well?

Do you want me to also add the `3.11` `PyPI` classifier? Or is that something that should be added after `3.11` is released?

**Comment by hugovk** [comment]
Personally I would add `3.11` (this is a pure Python package so it should be fine, if not, we'd better fix it!) and the other versions.

I also add:
```
Programming Language :: Python :: 3
Programming Language :: Python :: 3 :: Only
```

But some projects prefer to keep a minimal list. Maybe add them and we can always remove if the maintainers prefer?

**Comment by DanielNoord** [comment]
The 3.11 tests fail. Should I move those to another PR and fix the issues there?

**Comment by hugovk** [comment]
Ah right, I think that can be another PR/issue 👍 

We'll probably need something like these env vars for temporary workarounds:
 
https://github.com/python/bedevere/blob/6aebdb401e51d167d3f544e9f00105dcf8c16eed/tox.ini#L9-L15

**Comment by DanielNoord** [comment]
I'll wait on https://github.com/python/cherry-picker/pull/68 then.

Can we merge this without the test on `3.11` or should that be blocked by it?

**Review by ezio-melotti — APPROVED** [review]

**Review by hugovk — APPROVED** [review]

**Pull request merged**
